### ISSUE TITLE
woocommerce REST api oauth 1.0 failure 401

### ISSUE THREAD

**Issue by kiiwii** [bitnami/bitnami-docker-wordpress-nginx#18]
**Description**

**Steps to reproduce the issue:**

0.

> $ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress-nginx/master/docker-compose.yml
> $ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress-nginx/master/wordpress-server-block.conf
> $ docker-compose up

1. [docker-compose up] Good
2. [login wordpress admin] Good
3. [install woocommerce plugin] Good
4. [create woo API key pairs] Good
5. [with API key above, postman http://xxx.xxx.xxx/wp-json/wc/v3/products/categories] **Failure**

**Describe the results you received:**

{
    "code": "woocommerce_rest_authentication_error",
    "message": "Invalid signature - provided signature does not match.",
    "data": {
        "status": 401
    }
}

**Describe the results you expected:**

[
    {
        "id": 15,
        "name": "Uncategorized",
        "slug": "uncategorized",
        "parent": 0,
        "description": "",
        "display": "default",
        "image": null,
        "menu_order": 0,
        "count": 0,
        "_links": {
            "self": [
                {
                    "href": "http://xxx.xxx.xxx/wp-json/wc/v3/products/categories/15"
                }
            ],
            "collection": [
                {
                    "href": "http://xxx.xxx.xxx/wp-json/wc/v3/products/categories"
                }
            ]
        }
    }
]

**Additional information you deem important (e.g. issue happens only occasionally):**

Pretty sure:
the API key is absolute correct.

1. because I insert the same key into the another wordpress instance/db, and postman works well.
2. insert the same API key into bitnami-docker-wordpress (apache, NOT nginx), it also works.

one more thing:
modify the downloaded docker-compose.yml

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wpap:
    image: 'bitnami/wordpress:5'
    ports:
      - '19080:8080'
      - '19443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress-nginx:5'
    ports:
      - '80:8080'
      - '8443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - './conf/nginx/server_blocks/:/opt/bitnami/nginx/conf/server_blocks/'
      - './conf/fpm/www.conf:/opt/bitnami/php/etc/php-fpm.d/www.conf'
      - './conf/nginx/certs/:/opt/bitnami/nginx/conf/bitnami/certs/:ro'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

in the same docker compose stack, 3 containers: nginx, apache, mariadb
nginx, apache, share the only mariadb, still, the SAME API KEY.

postman access path:
apache:
host:19080->8080 *auth Works*

nginx:
host:8443->8443->**NOTE: proxy_pass to apache 8080**. *auth Works*
host:80->8080->proxy_pass to fpm. **auth Fails**

please fix this.
big fan of bitnami !
PEASE & <3

I think docker is not the cause. so omit below info.
If needed, i will post later.
**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
