### ISSUE TITLE
Unable to host HTTPS site using container

### ISSUE THREAD

**Issue by stunney** [bitnami/bitnami-docker-wordpress-nginx#23]
**Description**

Configuring a nginx server to expose port 8443 and server out a wordpress site does not seem to work.
I have custom certificates, which I am deploying as files to /opt/bitnami/nginx/conf/bitnami/certs/server.crt and server.key (same folder).
NGINX serves up the certificates correctly, however the home page does not load, I simply get the default NGINX landing page.

If I *only* go back to listen 8080; and remove the certificates lines from my wordpress-server-block.conf then the site is rendered properly but obviously the SSL certificate is not utilized.

**Steps to reproduce the issue:**

/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf
```
server {
  listen 8443 ssl;

  server_name myserver;

  root /opt/bitnami/wordpress;
  index index.php;

  ssl_certificate         /opt/bitnami/nginx/conf/bitnami/certs/server.crt;
  ssl_certificate_key     /opt/bitnami/nginx/conf/bitnami/certs/server.key;

  location / {
    try_files $uri $uri/ /index.php?q=$uri&$args;
  }

  if (!-e $request_filename)
  {
    rewrite ^/(.+)$ /index.php?q=$1 last;
  }

  location ~ \.php$ {
    fastcgi_pass localhost:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
}
```

docker-compose.yml
```
version: '3.6'
services:
  mariadb:
    image: 'bitnami/mariadb:10.4'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress-nginx:5.4.1'
    env_file:
      - ./environments/${DEPLOY_STAGE}/.env
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress:/bitnami/wordpress'      
      - './wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro'
      #- './nginx.conf:/opt/bitnami/nginx/conf/nginx.conf:rw'
      - './environments/${DEPLOY_STAGE}/secrets/my.crt:/opt/bitnami/nginx/conf/bitnami/certs/server.crt:ro'
      - './environments/${DEPLOY_STAGE}/secrets/my.key:/opt/bitnami/nginx/conf/bitnami/certs/server.key:ro'
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress:
    driver_opts:
      type: none
      device: /home/vagrant/bitnami/volumes/wordpress
      o: bind
  wordpress_bitnami_opt:
    driver_opts:
      type: none
      device: /home/vagrant/bitnami/volumes/wordpress_bitnami_opt
      o: bind
```

Using the above I get the standard NGINX landing page and the CORRECT SSL certificate.

/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf
```
server {
  listen 8080;

  server_name myserver;
  root /opt/bitnami/wordpress;
  index index.php;

  location / {
    try_files $uri $uri/ /index.php?q=$uri&$args;
  }

  if (!-e $request_filename)
  {
    rewrite ^/(.+)$ /index.php?q=$1 last;
  }

  location ~ \.php$ {
    fastcgi_pass localhost:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
}
```

I get the website being hosted by WordPress, but no SSL.

**Describe the results you received:**

I don't get SSL AND my WordPress site.  They seem to be mutually exclusive.

**Describe the results you expected:**

I would really like both :)

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 2
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.732GiB
 Name: a2plvcpnl15474
 ID: LQ3R:S472:4VXS:7FSC:4H4R:F6QC:PCAH:OGM2:CFZZ:KLA2:4R54:3MKE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version
docker-compose version 1.25.5, build unknown
docker-py version: 4.2.0
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Vagrant box (CentOS 7.7) running on Hyper-V (Windows 10)

Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.network "#{ENV.fetch('VAGRANT_HYPERV_NEWVM_SWITCH_NETWORK', 'public_network')}", :mac => "00155d01f23e", :bridge => "#{ENV.fetch('VAGRANT_HYPERV_NEWVM_SWITCH_NAME', 'Extern1')}"

  config.vm.define "control" do |control|
    control.vm.box = "centos/7"
    control.vm.provider "hyperv" do |machine|
      machine.vmname = "centos7-my-staging"
      machine.memory = "2048"
      machine.cpus = "2"
    end

    config.vm.provision "shell",
      path: "bootstrap_docker.sh"
    end

    config.vm.synced_folder ".", "/home/vagrant/my/", type: "rsync", rsync__exclude: ".git/"
    config.vm.synced_folder "../bitnami", "/home/vagrant/bitnami/", type: "rsync", rsync__exclude: ".git/"
  end

**Comment by rafariossaa** [comment]
Hi, 
  When you use the SSL configuration did you get some response from the server ? Probably wordpress is returning a redirection, and you will need to configure wordpress too.
  You can check this with `wget`, `curl` or in the network tab of your browser.

**Comment by stunney** [comment]
This just turned into a calamity here:
First off, in order to override the https.conf that is in the container by default, I have to run the container as root?
```
  wordpress:
    image: 'bitnami/wordpress-nginx:5.4.1'
    user: root
    env_file:
      - /home/vagrant/bitnami/environments/${DEPLOY_STAGE}/.env
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress:/bitnami/wordpress'      
      - './wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro'
      - './wordpress-server-block-https.conf:/opt/bitnami/nginx/conf/server_blocks/https.conf'

```

Not sure why.  Don't get me wrong, defaults are great but I would think that EVERYONE on the planet would want to override the defaults in https.conf.  Provide in in git just like the wordpress-server-block.conf.
Also, you can't mount the https.conf file as 'ro'.  The container spits back at you with yet another error.
I finally got everything to work with the following .conf file contents:

wordpress-server-block.conf
```
##Just HTTP Redirect to HTTPS now.
server {
  listen 8080;
  listen [::]:8080;
  server_name a2plvcpnl15474;#ufcw175.com www.ufcw175.com;

  root /opt/bitnami/wordpress;
  index index.php;


  location ~ /.well-known/acme-challenge {
    allow all;
    root /opt/bitnami/wordpress;
  }

  location / {
    rewrite ^ https://$host$request_uri? permanent;
  }
}
```

wordpress-server-block-https.conf (goes to https.conf in the container, as shown in the d-c.yml file above)
```
server {
  listen 8443 ssl;
  listen [::]:8443 ssl;

  ssl_certificate         /opt/bitnami/nginx/conf/bitnami/certs/server.crt;
  ssl_certificate_key     /opt/bitnami/nginx/conf/bitnami/certs/server.key;

  root /opt/bitnami/wordpress;
  index index.php;

  location / {
    try_files $uri $uri/ /index.php?q=$uri&$args;
  }

  if (!-e $request_filename)
  {
    rewrite ^/(.+)$ /index.php?q=$1 last;
  }

  location ~ \.php$ {
    fastcgi_pass localhost:9000;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
}
```

All seems resolved now.  Can I get a feature request out of this so that https.conf can easily be overwritten for those with custom certificates?  I have to believe that running the container as root is boo-bomb-bad.
