### ISSUE TITLE
Kubernetes : an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod {id}

### ISSUE THREAD

**Issue by himanshuahuja96** [bitnami/bitnami-docker-wordpress-nginx#28]
**Description**
I am trying to access the pod using port-forward on local machine and I'm getting this error
" an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 88416547af0029c801de5394ffe8da5f5859a74f27ff16dce953208dadcb2468, uid : exit status 1: 2020/05/27 11:55:25 socat[735685] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused"

I am seeing frequent CrashLoopBackOff also. But I am using standard configuration.

You can find my yaml file content below:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitnami-ngnix-wp
  labels:
    app: bitnami-ngnix-wp
spec:
  selector:
    matchLabels:
      app: bitnami-ngnix-wp
  template:
    metadata:
      labels:
        app: bitnami-ngnix-wp
    spec:
      containers:
        - name: web
          image: bitnami/wordpress-nginx:5
          volumeMounts:
            - mountPath: /bitnami/wordpress
              name: wp-pvc
            - name: bitnami-wordpress-ngnix-config
              mountPath: /opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf
          env:
            - name: MARIADB_HOST
              value: 127.0.0.1:3306
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
            - name: WORDPRESS_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: db_name
            - name: WORDPRESS_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: db_user
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: db_password
            # [END cloudsql_secrets]
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command: [
              "/cloud_sql_proxy",
              "-instances=wpscaleableonkubernetes:us-central1:wp-db=tcp:3306",
              # If running on a VPC, the Cloud SQL proxy can connect via Private IP. See:
              # https://cloud.google.com/sql/docs/mysql/private-ip for more info.
              "-ip_address_types=PRIVATE",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          # [START cloudsql_security_context]
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          # [END cloudsql_security_context]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: wp-pvc
          persistentVolumeClaim:
            claimName: wp-pvc
        - name: bitnami-wordpress-ngnix-config
          configMap:
            name: bitnami-wordpress-ngnix-config
```

My Cluster is on GKE and if i try other container images like Ngnix it works fine.

**Describe the results you received:**
I am trying to access the pod using port-forward on local machine and I'm getting this error
" an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 88416547af0029c801de5394ffe8da5f5859a74f27ff16dce953208dadcb2468, uid : exit status 1: 2020/05/27 11:55:25 socat[735685] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused"

I am seeing frequent CrashLoopBackOff also. But I am using standard configuration.

When i am visiting 127.0.0.1:8080on my local machine, its is throwing this error in browser.

This page isn’t working127.0.0.1 didn’t send any data.
ERR_EMPTY_RESPONSE

**Describe the results you expected:**

If I do port forward it has to show the wordpress screen.

**Additional information you deem important (e.g. issue happens only occasionally):**
CrashLoopBackOff 

**Version**
Client Version: v1.17.5
Server Version: v1.14.10-gke.36
