### ISSUE TITLE
Error executing postInstallation - permission denied - .buildcomplete file

### ISSUE THREAD

**Issue by hopingsteam** [bitnami/bitnami-docker-wordpress-nginx#31]
**Description**

I am trying to run this docker image on Amazon ECS. The first time when I installed it everything went smooth as it should. Today I wanted to add more extensions do the image (like adding vim, zip, redis, etc) and I encounter the following error when I try to run the image:

`Error executing 'postInstallation': EACCES: permission denied, open '/bitnami/wordpress/wp-content/plugins/.buildcomplete'`

**Steps to reproduce the issue:**

**1. Dockerfile**

```
FROM bitnami/wordpress-nginx

USER root

RUN apt-get update && apt-get install -y vim zip unzip git curl build-essential autoconf
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pecl install redis

RUN echo "\nextension=redis.so" >> /opt/bitnami/php/etc/php.ini

ENV MARIADB_HOST #####.amazonaws.com
ENV WORDPRESS_DATABASE_USER #####
ENV WORDPRESS_DATABASE_PASSWORD #####
ENV WORDPRESS_DATABASE_NAME #####

USER 1001

COPY ./wordpress-server-block.conf /opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf

#COPY ./bitnami/website /bitnami/wordpress

EXPOSE 8080 8443
```

**2. Dockerrun.aws.json**

```
{
  "AWSEBDockerrunVersion": 2,
  "volumes": [
    {
      "name": "wordpTPN",
      "host": {
        "sourcePath": "/var/app/current/bitnami/website"
      }
    }
  ],
  "containerDefinitions": [
    {
      "name": "wordpTPN",
      "image": "692442235404.dkr.ecr.eu-central-1.amazonaws.com/wordptpn:latest",
      "hostname": "wordpTPN",
      "essential": true,
      "memory": 900,
      "portMappings": [
        {
          "hostPort": 80,
          "containerPort": 8080
        },
        {
          "hostPort": 443,
          "containerPort": 8443
        }
      ],
      "mountPoints": [
        {
          "sourceVolume": "wordpTPN",
          "containerPath": "/bitnami/wordpress"
        }
      ]
    }
  ]
}
```

To reproduce the error, build the Dockerfile attached above and use the AWS ElasticBeanstalk service with the Dockerrun.aws.json. When the image is deployed, log in to the instance as root and type docker logs [container id].

**Describe the results you received:**

If I run the docker image locally (using docker-compose up -d or docker build + docker run) everything works fine. The problem appears when I'm deploying this image on AWS. Before adding the additional packages (vim, zip, etc) the image ran perfectly on AWS.

**Describe the results you expected:**

I expect the docker image to behave in the same way as it behaves on localhost..

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:00:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       369ce74
  Built:            Fri May 29 04:02:31 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:00:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       369ce74
  Built:            Fri May 29 04:02:31 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker-compose version` (if applicable):

```
not the case
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Using Amazon Elastic Beanstalk. The EC2 I'm deploying to is t2.micro .

**Comment by hopingsteam** [comment]
I've solved the issue by creating the following file called **init.config** in **.ebextenstions** folder

```
commands:
    create_post_dir:
        command: "mkdir /opt/elasticbeanstalk/hooks/appdeploy/post"
        ignoreErrors: true
    create_post_dir:
        command: "touch /var/app/current/mococo/.env;"
        ignoreErrors: true
files:
    "/opt/elasticbeanstalk/hooks/appdeploy/post/99_solvenami.sh":
        mode: "000755"
        owner: root
        group: root
        content: |
            #!/usr/bin/env bash
            pushd /var/app/current
            mkdir -p bitnami/wordpress
            sudo chown -R 1001:0 bitnami/
            popd
```

I hope that will help others that use AWS and encounter the same problem.
