### ISSUE TITLE
Issue with custom nginx server blocks

### ISSUE THREAD

**Issue by zbro-wtit422** [bitnami/bitnami-docker-wordpress-nginx#38]
I'm attempting to include a server block for https on port 8443. When I start the container, it will add an https.conf file in the server_blocks directory that overrides my config and displays the default nginx index.html. I do not want that to be displayed since it provides a bad actor information about the underlying web server.

I tried to mount a local directory with a server block for both http and https but the container fails to start. The post installation scripts appear to be attempting to add the https.conf but since the folder is ro, it fails. I've given it write permissions and it also fails. The only way I can get the container to start is to mount the specific server block conf file but it still will add the https.conf which I do not want.

Below is the error that I am see.

    $ docker logs <>

    Welcome to the Bitnami wordpress-nginx container
    Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx
    Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues
    
    nami    INFO  Initializing php
    nami    INFO  php successfully initialized
    nami    INFO  Initializing nginx
   Error executing 'postInstallation': Files to substitute resolved to an empty list

Below are the mounts for the wordpress/nginx bitnami container.

    volumes:
        - '/mnt/efs/fs1/wordpress_data:/bitnami/wordpress'
        - '/mnt/efs/fs1/nginx/server_blocks:/opt/bitnami/nginx/conf/server_blocks'

Any idea on how to resolve this issue?

**Comment by zbro-wtit422** [comment]
I was able to work around this issue by changing the include directive in nginx.conf to a different directory and then mounting my nginx folder at that location. I don't love the solution. It would be great if I didn't have to build my own container to get around this.

Below is the resulting Dockerfile.

    from docker.io/bitnami/wordpress-nginx:5-debian-10
   
    RUN sed -i 's/include  \"\/opt\/bitnami\/nginx\/conf\/server_blocks\/\*\.conf\"\;/include  \"\/opt\/bitnami\/nginx\/conf\/c_blocks\/\*\.conf\"\;/g' /opt/bitnami/nginx/conf/nginx.conf

**Comment by marcosbc** [comment]
Hi @zbro-wtit422, thanks for reporting this. We are planning to open-source the initialization scripts in the "rootfs" directory of this repo soon (like we did with [Drupal](https://github.com/bitnami/bitnami-docker-drupal-nginx/tree/master/9/debian-10/rootfs/opt/bitnami/scripts)), and as part of those changes, this should be properly supported.

However, we expect this will take some time (i.e. at least 2 months) since we have a lot of things on our backlog, and also keeping in mind all winter holidays. We'll keep this open by adding the `on-hold` tag to track this issue and ensure to update it when that is done.

**Comment by TheAggressive** [comment]
I'm guessing this has to do with this?

Hello, I'm running into an issue trying to do the steps mentioned in #17 as I would rather run WordPress with NGINX over Apache in helm. (side question, why apache by default and not option to use either?)

What I did is in my chart values, I changed the repository and tag to the follows
```
values.yaml
---

wordpress:
  image:
    registry: docker.io
    repository: bitnami/wordpress-nginx
    tag: "5.6.0"
```

I then made a config map to mount into `/opt/bitnami/nginx/conf/server_blocks` with the above `wordpress-server-block.conf` contents. 

```
server-block-configmap.yaml
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: wordpress-server-block
data:
  wordpress-server-block.conf: |-
    server {
      listen 0.0.0.0:80;
      server_name _;

      root /opt/bitnami/wordpress;
      index index.php;

      location / {
        try_files $uri $uri/ /index.php?q=$uri&$args;
      }

      if (!-e $request_filename)
      {
        rewrite ^/(.+)$ /index.php?q=$1 last;
      }

      location ~ \.php$ {
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }
    }
```

I then added `extraVolumes` and `extraVolumeMounts` to values.yaml

```
values.yaml
---

wordpress:
  extraVolumes:
    - name: wordpress-server-block-config
      configMap:
        name: wordpress-server-block

  extraVolumeMounts:
    - name: wordpress-server-block-config
      mountPath: /opt/bitnami/nginx/conf/server_blocks
      readOnly: true
```

When I `helm install`... the WordPress Pod status ends up `CrashLoopBackOff`

I then looked at the logs and this is what I see:
```
> kubectl logs wordpress-795c489b6-z9fd6

Welcome to the Bitnami wordpress-nginx container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress-nginx
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress-nginx/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing nginx
Error executing 'postInstallation': Files to substitute resolved to an empty list
```

Any idea to get this working without building a custom docker image? I would really love to use your WordPress with NGINX image over the Apache version for optimal performance.

Is there a way we can help open-source the initialization scripts in the "rootfs" directory of this repo to help expedite the process? 

Thank you for all you guys do!

**Comment by dani8art** [comment]
Hi @zbro-wtit422 could you use `subpath` to mount the file directly instead of overriding the entire directory?

```
  extraVolumeMounts:
    - name: wordpress-server-block-config
      mountPath: /opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf
      subPath: wordpress-server-block.conf
      readOnly: true
```

**Comment by TheAggressive** [comment]
@dani8art that worked!

I also had to update the `wordpress-server-block.conf` to the following to listen on port `8080` instead of `80`

```
server-block-configmap.yaml
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: wordpress-server-block
data:
  wordpress-server-block.conf: |-
    server {
      listen 0.0.0.0:8080;
      ...
```
Is there a way to add 443 in there as well? Anytime I port forward to 8443 I get the default nginx welcome html page. I'm guessing that is caused by the default `https.conf` in `/opt/bitnami/nginx/conf/server_blocks/` directory?

I tried to overwrite the file using the same approach as the `wordpress-server-block.conf` but no go as it starts the crash loop again. The configuration I tried was as follows:

```
server-block-configmap-https.yaml
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: wordpress-server-block-https
data:
  https.conf: |-
    server {
        listen 8443 ssl;
        listen [::]:8443 ssl;

        ssl_certificate             /opt/bitnami/nginx/conf/bitnami/certs/server.crt;
        ssl_certificate_key         /opt/bitnami/nginx/conf/bitnami/certs/server.key;
        ssl_session_cache           shared:SSL:1m;
        ssl_session_timeout         5m;
        ssl_ciphers                 HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers   on;

        root /opt/bitnami/wordpress;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?q=$uri&$args;
        }

        if (!-e $request_filename)
        {
          rewrite ^/(.+)$ /index.php?q=$1 last;
        }

        location ~ \.php$ {
            fastcgi_pass localhost:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
```

```
values.yaml
---

extraVolumes:
    ...
    - name: wordpress-server-block-config-https
      configMap:
        name: wordpress-server-block-https

  ## Extra volume mounts to add to the container
  ##
  extraVolumeMounts:
    ...
    - name: wordpress-server-block-config-https
      mountPath: /opt/bitnami/nginx/conf/server_blocks/https.conf
      subPath: https.conf
      readOnly: true
```

I guess that's the issue @zbro-wtit422 is having. Can't add your own `https.conf` in just a different use case of docker instead of kubernetes?
