### ISSUE TITLE
NGINX_HTTP_PORT_NUMBER: privileged port requested

### ISSUE THREAD

**Issue by antonio24073** [bitnami/bitnami-docker-wordpress-nginx#52]
Hi, 
I'm trying to change the nginx port number from 8080 to 80 and 8443 to 443. But I got this error:
```
wordpress 23:39:43.70 INFO  ==> ** Starting WordPress setup **
wordpress 23:39:43.71 INFO  ==> Validating settings in NGINX_* env vars
wordpress 23:39:43.72 ERROR ==> An invalid port was specified in the environment variable NGINX_HTTP_PORT_NUMBER: privileged port requested
```

`server_blocks/wordpress-https-server-block.conf`
```
server {
    listen 443 ssl default_server;
```
`server_blocks/wordpress-server-block.conf`
```
server {
    listen 80 default_server;
```
`Dockerfile`
```
FROM bitnami/wordpress-nginx
ENV NGINX_HTTP_PORT_NUMBER=80
ENV NGINX_HTTPS_PORT_NUMBER=443
EXPOSE 80 443
```
`docker-compose.yml`
```
version: '3.8'
services: 
    wp:
        ports:
            - 127.0.0.xx:80:80
            - 127.0.0.xx:443:443
        volumes:
            - ./wp/server_blocks:/opt/bitnami/nginx/conf/server_blocks
        networks:
            wordpress_network:
                ipv4_address: 172.16.238.xx
                ipv6_address: 2001:3984:3989::xx
networks:
    wordpress_network:
        driver: bridge
        ipam:
            config:
                - subnet: "172.16.238.0/24"
                - subnet: "2001:3984:3989::/64"
```

I have a similar issue with bitnami/phpmyadmin but it is with apache. I have other containers and these changes works fine. This problem is with bitnami containers only. I readed a lot of docs and nothing.
