### ISSUE TITLE
Container initialization is very very slow

### ISSUE THREAD

**Issue by nicokaiser** [bitnami/bitnami-docker-wordpress-nginx#6]
**Description**

Container start up is very very slow.

**Steps to reproduce the issue:**

1. Start the container (with previously used volume)

**Describe the results you received:**

The container initialized nginx, mysql-client and wordpress. The wordpress initialization takes several minutes (!) to finish, even if there are not that many files in the WordPress directory.

```
nami    INFO  Initializing nginx
nami    INFO  nginx successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
... (minutes later) …
wordpre INFO  WordPress has been already initialized, restoring...
…
```

**Describe the results you expected:**

The initialization should either finish after some seconds, or not happen at all (the `/bitnami/wordpress/.initialized` file is there, so I don't expect WordPress to be initialized again)

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:34:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 30
 Running: 23
 Paused: 0
 Stopped: 7
Images: 42
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: 5o7ej144z7i3k7a2mr9b1whde
 Is Manager: true
 ClusterID: ihz69rerkuu9ms5k0ydqkaz8o
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 82.135.8.63
 Manager Addresses:
  82.135.8.63:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.801GiB
Name: server
ID: UIPI:DIKQ:34LS:Z65A:3VHZ:S6VL:XHME:Z6AC:53NG:3WHR:CCMM:QHW7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by rafariossaa** [comment]
Hi @nicokaiser ,
  Have you make any change to the default docker-compose file ? If yes, please could you provide it ?
  You said you are using a previous volumen, have you added files? (for example a copy from other wordpress installation).

**Comment by nicokaiser** [comment]
Yes, I copied a previous wordpress installation. I copied the `wp-content` directory and modified the `wp-config.php` to match the one generated by a new Bitnami installation.

The docker-compose file is pretty much like the one supplied with this container:

```
version: '3.5'
services:
  wordpress:
    image: bitnami/wordpress-nginx:5
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=myblog
      - WORDPRESS_DATABASE_PASSWORD=[redacted]
      - WORDPRESS_DATABASE_NAME=myblog_wordpress
      - WORDPRESS_BLOG_NAME=My Blog
      - WORDPRESS_EMAIL=user@example.com
      - WORDPRESS_FIRST_NAME=Firstname
      - WORDPRESS_HOST=example.com
      - WORDPRESS_LAST_NAME=Lastname
      - WORDPRESS_USERNAME=user
      - SMTP_HOST=mail.example.com
      - SMTP_PORT=587
      - SMTP_USER=noreply@example.com
      - SMTP_PASSWORD=[redacted]
      - SMTP_PROTOCOL=tls
    networks:
      - web
      - mariadb-network
    volumes:
      - wordpress_data:/bitnami
      - ./wordpress-vhosts.conf:/bitnami/nginx/conf/vhosts/wordpress-vhosts.conf
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.port=80'
      - 'traefik.backend=myblog'
      - 'traefik.frontend.rule=Host:example.com,www.example.com'
      - 'traefik.frontend.headers.SSLHost=example.com'
      - 'traefik.frontend.headers.SSLForceHost=true'
      - 'traefik.enable=true'
networks:
  mariadb-network:
    external: true
  web:
    external: true
volumes:
  wordpress_data:
    driver: local
```
