### ISSUE TITLE
Container is deleting my files in wp-content folder

### ISSUE THREAD

**Issue by yongzhang** [bitnami/bitnami-docker-wordpress-nginx#68]
Hi, I deploy container in kubernetes like this:

```
...
          env:
          - name: WORDPRESS_SKIP_BOOTSTRAP
            value: "yes"
          - name: WORDPRESS_DATA_TO_PERSIST
            value: "wp-content"

...

          volumeMounts:
          - name: data
            mountPath: /bitnami/wordpress/wp-content
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
```

I moved from official docker image to bitnami, my previous mode of `wp-content` is 33, so ignore the permission error in below picture:
![image](https://user-images.githubusercontent.com/15604715/142569635-ec797f88-ae21-4b08-9018-8fe65163fef9.png)

But I was scared about the behavior that container is deleting my files inside `wp-content` when starting, I'm not sure what's going on here, please help, thanks.
