### ISSUE TITLE
Incorrect WP_HOME and WP_SITEURL values when behind a reverse proxy

### ISSUE THREAD

**Issue by ziodave** [bitnami/bitnami-docker-wordpress-nginx#86]
### Name and Version

bitnami/wordpress-nginx:6

### What steps will reproduce the bug?

1. Configure a docker-compose.yaml with a wordpress-nginx container and an nginx reverse proxy container
2. Configure nginx to reverse proxy the wordpress-nginx container
3. Try to open the site
4. The site will open but static assets will be broken because WordPress is configured using the local hostname instead of the one configured in the nginx reverse proxy

### What is the expected behavior?

Expected behavior is for the setup script to recognize the proper hostname using the relevant HTTP headers.

### What do you see instead?

A broken WP install.

**Comment by carrodher** [comment]
Thanks for creating this issue and the associated PR, we will review it and provide feedback

**Comment by fmulero** [comment]
Hi @ziodave Thanks a lot for your contribution.

Could you share your docker-compose.yaml with the test scenario? It would be very useful to validate your PR and also we could include it in our CICD tests

**Comment by ziodave** [comment]
Of course. I use _minica_ to issue a certificate for a local development, e.g. `wordpress.www.localhost` (pointing to 127.0.0.1). The `cert.pem` and `key.pem` files a restored in a local folder `.docker/nginx/conf.d` mapped to the nginx container along with the reverse proxy configuration.

docker-compose.yaml:
```
version: "3.9"

services:
  db:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress

  wordpress:
    image: bitnami/wordpress-nginx:6
    depends_on:
      - db
    environment:
      WORDPRESS_DATABASE_HOST: db
      WORDPRESS_DATABASE_USER: wordpress
      WORDPRESS_DATABASE_PASSWORD: password
      WORDPRESS_DATABASE_NAME: wordpress
      WORDPRESS_DEBUG: "1"
      WORDPRESS_ENABLE_HTTPS: "yes"

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.21.5
    ports:
      - "443:443"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d

volumes:
  db-data:
```

.docker/nginx/conf.d/wordpress.conf:
```
server {
    listen              443 ssl http2;
    server_name         *.www.localhost;
    ssl_certificate     conf.d/_.www.localhost/cert.pem;
    ssl_certificate_key conf.d/_.www.localhost/key.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 50M;

    root /var/www/html;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://wordpress:8080/;

        proxy_connect_timeout       300;
        proxy_send_timeout          300;
        proxy_read_timeout          300;
        send_timeout                300;
    }

}
```

I can provide sample key.pem and cert.pem if necessary.
