### ISSUE TITLE
404 on assets folder

### ISSUE THREAD

**Issue by realandrew** [bitnami/bitnami-docker-wordpress-nginx#90]
### Name and Version

bitnami/wordpress-nginx:6.0.1

### What steps will reproduce the bug?

Env: macOS 12.0.1 (Intel)

Config:
```yml
version: '3'
services:
  wp:
    image: bitnami/wordpress-nginx:latest
    ports:
      - 8080:8080
      - 8433:8433
    restart: always
    volumes:
      - ./:/bitnami/wordpress
    environment:
      WORDPRESS_DATABASE_HOST: whatever
      MARIADB_HOST: whatever
      WORDPRESS_DATABASE_PORT_NUMBER: 3306
      MARIADB_PORT_NUMBER: 3306
      WORDPRESS_DATABASE_USER: root
      WORDPRESS_DATABASE_PASSWORD: whatever
      WORDPRESS_DATABASE_NAME: whatecer
      WORDPRESS_SKIP_BOOTSTRAP: true
      WORDPRESS_DATA_TO_PERSIST: ''
      BITNAMI_DEBUG: yes
```

### What is the expected behavior?

Files in the assets folder load correctly. Assets is a top level directory just like wp-content which works fine, both have the correct permissions set.

### What do you see instead?

404 errors returned for files in the assets folder. `http://localhost:8080/assets/images/slider_arrow.png 404 (Not Found)`

### Additional information

This also happens with the bitnami-wordpress container that uses Apache. It should just work but it doesn't, I'm not sure if the default config for apache/nginx that comes with the container just isn't setup to support this or I'm just missing something obvious. Any help is appreciated.
